import PackagePlugin
import Foundation

@main
struct BuildVersionPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        let versionFile = context.package.directoryURL.appending(path: "VERSION")
        let outputFile = context.pluginWorkDirectoryURL.appending(path: "GeneratedVersion.swift")

        return [
            .buildCommand(
                displayName: "Generate version from VERSION file",
                executable: URL(fileURLWithPath: "/bin/bash"),
                arguments: [
                    "-c",
                    """
                    VERSION=$(cat "\(versionFile.path)" | tr -d '\\n')
                    cat > "\(outputFile.path)" << EOF
                    // Auto-generated by BuildVersionPlugin - do not edit
                    enum GeneratedVersion {
                        static let version = "$VERSION"
                    }
                    EOF
                    """
                ],
                inputFiles: [versionFile],
                outputFiles: [outputFile]
            )
        ]
    }
}
